version: "3.9"

services:

  application:
    container_name: demo.app
    image: 065659108092.dkr.ecr.us-east-1.amazonaws.com/dotnet_app:tag
    restart: unless-stopped
    ports:
      - 5001:5001
    networks:
      - demonet
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:5001

  react:
    depends_on:
    - application
    container_name: demo.react
    image: 065659108092.dkr.ecr.us-east-1.amazonaws.com/react_app:tag
    restart: unless-stopped
    ports:
      - 80:3000
    networks:
      - demonet
    environment:
      REACT_APP_BACKEND_HOST: 3.89.90.9
    stdin_open: true
networks:
  demonet:
    name: demonet
